name: packetsniff-test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.0
    
    - name: setup-os
      run: sudo apt install -y libpcap-dev

    - name: Install dependencies
      run: go mod tidy

    - name: Run test
      run: go test ./... -v
  